from PyQt5.QtGui import QColor
from PyQt5.QtCore import Qt

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

# Ustawienia komórek
DEFAULT_CELL_RADIUS = 30
POINTS_PER_STRENGTH = 10
MAX_CELL_POINTS = 50 

# Kolory komórek
COLOR_PLAYER = QColor(0, 200, 100)
COLOR_ENEMY = QColor(200, 50, 50)
COLOR_NEUTRAL = QColor(200, 150, 0)

# Nowe stałe kolory:
COLOR_BUTTON_LEFT = QColor(50, 50, 150)
COLOR_BUTTON_RIGHT = QColor(80, 80, 180)
COLOR_BG_TOP = QColor(230, 190, 255)
COLOR_BG_BOTTOM = QColor(100, 0, 150)
COLOR_CONN_PLAYER = QColor(0, 100, 0)
COLOR_CONN_ENEMY = QColor(139, 0, 0)
COLOR_CONN_CONFLICT_LEFT = QColor(0, 255, 0)
COLOR_CONN_CONFLICT_RIGHT = QColor(139, 0, 0)
COLOR_DOT_PLAYER = QColor(144, 238, 144)
COLOR_DOT_ENEMY = QColor(255, 99, 71)
COLOR_HINT_PRIMARY = QColor(255, 215, 0)
COLOR_HINT_SECONDARY = QColor(255, 100, 0)
COLOR_HIGHLIGHT = QColor(255, 255, 0)
COLOR_FROZEN_OUTLINE = QColor(0, 150, 255)

# Ustawienia przycisku przełącznika
SWITCH_BUTTON_WIDTH = 60
SWITCH_BUTTON_HEIGHT = 30
COLOR_SWITCH_ON = QColor(0, 150, 136)
COLOR_SWITCH_OFF = QColor(200, 200, 200)

# Ustawienia menu
MENU_TITLE_FONT_SIZE = 36
MENU_LEVEL_TITLE_FONT_SIZE = 24
MENU_SWITCH_LABEL_FONT_SIZE = 16
MENU_TITLE_Y_POSITION = 100
MENU_LEVEL_BUTTON_WIDTH = 300

# Ustawienia sceny gry
FRAME_INTERVAL_MS = 16
POINTS_INTERVAL_MS = 2000
TURN_TIMER_INTERVAL_MS = 1000
TURN_DURATION_SECONDS = 10

# Ustawienia edytora
EDITOR_GRID_SIZE = 50

# Ustawienia czcionek
FONT_FAMILY = "Arial"
BUTTON_FONT_SIZE = 14
EDITOR_TITLE_FONT_SIZE = 24
EDITOR_SUBTITLE_FONT_SIZE = 16
EDITOR_INSTRUCTION_FONT_SIZE = 12
GAME_TURN_FONT_SIZE = 16
GAME_OVER_FONT_SIZE = 36

# Czas trwania zamrożenia w sekundach
FREEZE_DURATION_SECONDS = 10  

# Nazwy powerupów wyświetlane w komunikacie o aktywowanym powerupie
POWERUP_FREEZE = "mrożący"
POWERUP_TAKEOVER = "przejmujący"
POWERUP_ADD_POINTS = "punktujący"
POWERUP_NEW_CELL = "stawiający"

# Dodana stała określająca maksymalną odległość dla kopiowania komórki  //FACTOR*radius
NEW_CELL_COPY_RANGE_FACTOR = 5

# Stałe pozycjonowania elementów menu
MENU_TITLE_Y_POSITION = 50
MENU_SWITCH_LABEL_Y_POSITION = 120
MENU_SWITCH_Y_POSITION = 150
MENU_LEVEL_TITLE_Y_POSITION = 200
MENU_LEVEL_START_Y_POSITION = 250
MENU_MODE_TITLE_Y_OFFSET = 10
MENU_RADIO_FIRST_Y_OFFSET = 50
MENU_RADIO_SECOND_Y_OFFSET = 25
MENU_IP_Y_OFFSET = 30
MENU_PORT_Y_OFFSET = 70
MENU_IP_X_OFFSET = 0
MENU_REPLAY_TITLE_Y_OFFSET = 115
MENU_REPLAY_BUTTON_Y_OFFSET = 50

# Stałe skrótów klawiszowych
KEY_HINT =  Qt.Key_H
KEY_QUICKSAVE = Qt.Key_Q
KEY_QUICKLOAD = Qt.Key_L
KEY_ESCAPE = Qt.Key_Escape
KEY_INFO = Qt.Key_I

# Skróty w edytorze poziomów
KEY_DELETE = Qt.Key_Delete
KEY_SAVE = Qt.Key_S
KEY_EDITOR_ESCAPE = Qt.Key_Escape